## JDBC Connection Setup

spring.datasource.url= jdbc:postgresql://localhost:5432/smartcrop
spring.datasource.username= postgres
spring.datasource.password= postgres

#spring.datasource.url= jdbc:postgresql://localhost:5432/local
#spring.datasource.username= local
#spring.datasource.password= password

## Hibernate
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto= update
logging.level.org.hibernate.SQL= DEBUG
spring.jpa.properties.hibernate.format_sql=true

## Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartcropp@gmail.com
spring.mail.password=qhhrpdvarihnpsqe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.application.siteURL=http://192.168.2.143:8080

com.smart.crop.admin.email=smartcropp@gmail.com
